[phases.setup]
# Usa Node.js 22.12 (mínimo suportado pelo Vite 7.x)
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run preview -- --port 80 --host"
